### ISSUE TITLE
Not working on Linux (specifically the Steam Deck)

### ISSUE THREAD

**Issue by Genera1-Dynamics** [zTomma/WeirdcoreHUD#10]
I use a Steam Deck (as well as Linux in general) and I love the style of this HUD, but I can't get it to go. I changed the resolution to 720p 16:9. I am using a config. Any help would be appreciated.

**Comment by Genera1-Dynamics** [comment]
NVM, I got it to work by using Proton and not running TF2 natively on Linux.

**Comment by Genera1-Dynamics** [comment]
Ok, you can't run TF2 on Proton for some reason, it won't let you join servers. So, I can't use the HUD, bummer. A Linux version of this HUD would be really nice. :)

**Comment by zTomma** [comment]
dw i will fix it

**Comment by OhaDerErste** [comment]
You can (apparently) fix it by renaming the huds folder to an lowercase name

**Comment by Genera1-Dynamics** [comment]
Thanks!

**Comment by Genera1-Dynamics** [comment]
It runs perfectly now that I changed it to lowercase.
16:10 aspect ratio is bugged, so using 16:9 for now.
