### ISSUE TITLE
I want to press E on the class select screen to edit that class's loadout

### ISSUE THREAD

**Issue by sarahkittyy** [zTomma/WeirdcoreHUD#2]

**Comment by sarahkittyy** [comment]
and hovering the class should show its preview instead of only after it's clicked

**Comment by h43ven** [comment]
The new update fixed this, right? If correct, then either sarah or tomma should close this issue.

**Comment by zTomma** [comment]
> The new update fixed this, right? If correct, then either sarah or tomma should close this issue.

Oh god i forgot to close these, now in going to sleep i'll to that tomorrow, thanks for warning me 

Edit: just closed it, it was easier than expected :P
